@url = https://localhost:8000

###
GET {{url}}/seed
###
POST {{url}}/admins
Content-Type: application/json

{
    "username":"Kamau",
    "password":"1234",
    "email":"kamaa@gmail.com",
    "last_login":"2025-05-23"
}