@url = http://localhost:8000/api/v1

### Root
@AccessToken  =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEzLCJlbWFpbCI6ImFuZHJlYXN0YWlsYXM5NkBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NDk1NjYwNDUsImV4cCI6MTc0OTU2OTA0NX0.HxvioFiYTVzEvz8pR2BzwEHFaNkL3NaiAWcvCvgTmcw
@RefreshToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEzLCJlbWFpbCI6ImFuZHJlYXN0YWlsYXM5NkBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NDk1NjYwNDUsImV4cCI6MTc1MDE3MDg0NX0.1o-mgQDhxnAysjeHFhmvgxBKN220pM0aFrEVFy20iKA

###

GET {{url}}/users
Authorization: Bearer {{AccessToken}}

###
GET {{url}}/users/1
Authorization: Bearer {{AccessToken}}

###
POST {{url}}/users
Content-Type: application/json

{
    
    "password": "testpass",
    "email": "user@example.com",
    "first_name": "John",
    "last_name": "Doe",
    "status": "active",
    "phone_number": "1234567890",
    "profile_picture": "http://example.com/profile.jpg"
}

###
POST {{url}}/users
Content-Type: application/json

{
    
    "password": "testpass",
    "email": "admin@example.com",
    "first_name": "Jerry",
    "last_name": "Kim",
    "status": "active",
    "role": "admin",
    "phone_number": "1234567890",
    "profile_picture": "http://example.com/profile.jpg"
}


###
POST {{url}}/users
Content-Type: application/json

{
    
    "password": "testpass",
    "email": "andreastailas96@gmail.com",
    "first_name": "Andreas",
    "last_name": "Tailas",
    "status": "active",
    "role": "admin",
    "phone_number": "1234567890",
    "profile_picture": "http://example.com/profile.jpg"
}
###
PATCH {{url}}/users/1
Content-Type: application/json

{
    "username": "updateduser"
}

###
DELETE {{url}}/users/1


###

### LOGIN a new user
POST {{url}}/auth/signin
Content-Type: application/json

{
  "email": "andreastailas96@gmail.com",
  "password": "newpassword123"
}

###
POST {{url}}/auth/reset-password
Authorization: Bearer {{AccessToken}}
Content-Type: application/json

{
    "newPassword": "newpassword123",
    "confirmPassword": "newpassword123",
    "token":"{{RefreshToken}}"
}

###
POST {{url}}/auth/forgot-password
Authorization: Bearer {{AccessToken}}
Content-Type: application/json

{
    "email": "andreastailas96@gmail.com"
}
###
GET {{url}}/users
Authorization: Bearer {{AccessToken}}

### refresh token
GET {{url}}/auth/refresh?id=22
Authorization: Bearer {{RefreshToken}}
### Guest Users
GET {{url}}/guest-users

###
GET {{url}}/guest-users/22
Authorization: Bearer {{AccessToken}}

###
POST {{url}}/guest-users
Authorization: Bearer {{AccessToken}}
Content-Type: application/json

{
    "first_name": "Jammal",
    "last_name": "Doe",
    "email": "jam@gmail.com",
    "phone_number": "1234567890"
}

###
PATCH {{url}}/guest-users/22
Authorization: Bearer {{AccessToken}}
Content-Type: application/json

{
    "first_name": "Updated Guest"
}

###
DELETE {{url}}/guest-users/1

### Vehicle Brands
GET {{url}}/vehicle-brands

###
GET {{url}}/vehicle-brands/11
Authorization: Bearer {{AccessToken}}

###
POST {{url}}/vehicle-brands
Authorization: Bearer {{AccessToken}}
Content-Type: application/json

{
    "brand_name": "Mercedez-Benz"
}

###
PATCH {{url}}/vehicle-brands/1
Content-Type: application/json

{
    "name": "Updated Brand"
}

###
DELETE {{url}}/vehicle-brands/1

### Vehicles
GET {{url}}/vehicles
Authorization: Bearer {{AccessToken}}

###
GET {{url}}/vehicles/21
Authorization: Bearer {{AccessToken}}

###
POST {{url}}/vehicles
Authorization: Bearer {{AccessToken}}
Content-Type: application/json

{
    "vehicle_brandId": 11,
    "model": "Model X",
    "color": "Red",
    "price_per_day": 100,
    "availability": true
}

###
PATCH {{url}}/vehicles/1
Content-Type: application/json

{
    "model": "Updated Model"
}

###
DELETE {{url}}/vehicles/3
Authorization: Bearer {{AccessToken}}

### Bookings
GET {{url}}/bookings
Authorization: Bearer {{AccessToken}}

###
GET {{url}}/bookings/13
Authorization: Bearer {{AccessToken}}

###
POST {{url}}/bookings
Content-Type: application/json
Authorization: Bearer {{AccessToken}}

{
    "vehicleId": 4,
    "userId": 3,
    "status": "confirmed",
    "booking_date": "2025-05-23",
    "return_date": "2025-05-30"
}

###
PATCH {{url}}/bookings/1
Content-Type: application/json

{
    "status": "cancelled"
}

###
DELETE {{url}}/bookings/4
Authorization: Bearer {{AccessToken}}

### Testimonials
GET {{url}}/testimonials
Authorization: Bearer {{AccessToken}}

###
GET {{url}}/testimonials/1
Authorization: Bearer {{AccessToken}}

###
POST {{url}}/testimonials
Content-Type: application/json
Authorization: Bearer {{AccessToken}}

{
    "userId": 12,
    "testimonial": "Great service!",
    "status": "active",
    "created_at": "2025-05-23T10:00:00Z"
}

###
PATCH {{url}}/testimonials/1
Content-Type: application/json

{
    "content": "Updated testimonial"
}

###
DELETE {{url}}/testimonials/1

### Contact Us Queries
GET {{url}}/contact-us-queries
Authorization: Bearer {{AccessToken}}

###
GET {{url}}/contact-us-queries/1
Authorization: Bearer {{AccessToken}}

###
POST {{url}}/contact-us-queries
Content-Type: application/json
Authorization: Bearer {{AccessToken}}

{
    "query_message": "I have a question."
}

###
PATCH {{url}}/contact-us-queries/1
Content-Type: application/json

{
    "message": "Updated question."
}

###
DELETE {{url}}/contact-us-queries/1

### Subscribers
GET {{url}}/subscribers

###
GET {{url}}/subscribers/35

###
POST {{url}}/subscribers
Content-Type: application/json
Authorization: Bearer {{AccessToken}}

{
    "email": "subscriber@example.com",
    "userId": 13
}

###
PATCH {{url}}/subscribers/1
Content-Type: application/json

{
    "email": "updated@example.com",
    
}

###
DELETE {{url}}/subscribers/1

### Payments
GET {{url}}/payments

###
GET {{url}}/payments/13

###
POST {{url}}/payments
Content-Type: application/json

{
    "userId": 1,
    "amount": 100
}
###
PATCH {{url}}/payments/1
Content-Type: application/json

{
    "amount": 200
}
###
DELETE {{url}}/payments/1

### Ratings
GET {{url}}/ratings
###
GET {{url}}/ratings/1
###
POST {{url}}/ratings
Content-Type: application/json

{
    "userId": 1,
    "vehicleId": 1,
    "score": 5
}
###
PATCH {{url}}/ratings/1
Content-Type: application/json

{
    "score": 4
}
###
DELETE {{url}}/ratings/1

### Seed
POST {{url}}/seed

### Logs
GET {{url}}/logs
###
DELETE {{url}}/logs

### Cache
POST {{url}}/cache
Authorization: Bearer {{AccessToken}}
Content-Type: application/json

{
    "key": "testkey",
    "value": "testvalue"
}
###
GET {{url}}/cache/testkey
###
DELETE {{url}}/cache/testkey