@url = https://car-rental-backend-1-5axa.onrender.com

###
POST {{url}}/seed
###
POST {{url}}/admins
Content-Type: application/json

{
    "username":"Kamau",
    "password":"1234",
    "email":"kamaa@gmail.com",
    "last_login":"2025-05-23"
}