

services:
  car-rental-db:
    image: postgres:15-alpine
    container_name: car-rental
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: car-rental-db
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8'
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - app-network

volumes:
  pgdata:
    name: car-rental-db-data
    driver: local

networks:
  app-network:
    driver: bridge
