version: '3.8'

services:
  car-rental-db:
    image: postgres:15-alpine
    container_name: car-rental-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: car-rental-db
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data  
    networks:
      - app-network

  redis:
      image: redis:8.0-alpine
      container_name: redis-cache
      restart: unless-stopped
      command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
      ports:
        - "6379:6379"
      volumes:
        - redis-data:/data
      networks:
        - app-network

volumes:
  pgdata:
    name: car-rental-db
    driver: local
  redis-data:
    name: redis-cache-data
    driver: local

networks:
  app-network:
    driver: bridge